# Build settings

#markdown: kramdown
title: Portage Dataverse Curation Guide
remote_theme: reseau-portage-network/just-the-docs
logo: /assets/img/Portage_logo_Tagline_rgb_bilingual.png
search_enabled: true
heading_anchors: true


#github_repo_url: "https://github.com/reseau-portage-network/dataverse-curation"
plugins:
 # - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag
#defaults:
#  - scope:
#      path: "assets/img"
#    values:
#      image: true

# Site settings

title_en: Portage Dataverse Curation Guide
title_fr: Guide pour la curation dans Dataverse
author: Portage Network
baseurl: /dataverse-curation
url: "https://reseau-portage-network.github.io"
email: "portage@carl-abrc.ca"#
description: #A simple and awesome blog theme powered by jekyll.
keywords: # [""]
permalink: pretty
exclude: ["README.md"]
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/reseau-portage-network/dataverse-curation" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immedia
# lang: en
# languages: ["en", "fr"]
# permalink: pretty

#collections:
#  posts:
#    output: true
#    permalink: /:path

#social:
#  github_username: reseau-portage-network

license_url: "http://creativecommons.org/licenses/by/4.0/"
license_name: "Creative Commons Attribution 4.0 International License"
license_image_url: "https://i.creativecommons.org/l/by/4.0/88x31.png"