title: Dataverse Curation Guide
subtitle: A guide for dataverse curators
#description: A guide for dataverse curators
# keywords: # [""]

remote_theme: reseau-portage-network/just-the-docs
colour_scheme: light
#logo: /assets/img/Portage_logo_Tagline_rgb_bilingual.png
search_enabled: true
heading_anchors: true

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Site settings

#title_en: Portage Dataverse Curation Guide
#title_fr: Guide pour la curation dans Dataverse
#author: Portage Network
#baseurl: /dataverse-curation
#url: "https://reseau-portage-network.github.io"
#email: "portage@carl-abrc.ca"#
# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "View this content on GitHub"
gh_edit_repository: "https://github.com/reseau-portage-network/dataverse-curation" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immedia
# lang: en
# languages: ["en", "fr"]
# permalink: pretty

#collections:
#  posts:
#    output: true
#    permalink: /:path

#social:
#  github_username: reseau-portage-network

license_url: "http://creativecommons.org/licenses/by/4.0/"
license_name: "Creative Commons Attribution 4.0 International License"
license_image_url: "https://i.creativecommons.org/l/by/4.0/88x31.png"